M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu20.04.1} date Mo 24 Jul 2023 18:38:09 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-24T18:38:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
%
G90
G05
T1
X77.969Y-63.378
X80.969Y-63.378
T0
M30
